# Generated by Django 5.1.6 on 2025-03-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='tahun_lulus',
            new_name='graduation_year',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='jurusan',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='nama',
        ),
        migrations.AddField(
            model_name='alumni',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
