# Generated by Django 5.1.6 on 2025-03-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0002_rename_tahun_lulus_alumni_graduation_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='graduation_year',
            new_name='angkatan',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='company',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='name',
        ),
        migrations.AddField(
            model_name='alumni',
            name='nama',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='pekerjaan',
            field=models.CharField(default='Tidak Diketahui', max_length=255),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
