# Generated by Django 5.1.6 on 2025-03-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0003_rename_graduation_year_alumni_angkatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='nama',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='pekerjaan',
            field=models.CharField(max_length=255),
        ),
    ]
