# Generated by Django 5.1.6 on 2025-04-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0004_alter_alumni_nama_alter_alumni_pekerjaan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='pekerjaan',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='angkatan',
            new_name='graduation_year',
        ),
        migrations.AddField(
            model_name='alumni',
            name='job_position',
            field=models.CharField(default='Belum Diisi', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='major',
            field=models.CharField(default='Belum Diisi', max_length=255),
            preserve_default=False,
        ),
    ]
